project:
  type: website

website:
  title: "Jeff Lambe"
  navbar:
    left:
      - href: index.qmd
        text: Jeff
      - education.qmd
      - publications.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

